### ISSUE TITLE
submitting orders 

### ISSUE THREAD

**Issue by mabdalla** [johnsolo15/AZ-Penguins#6]
PL/SQL error when try to submit orders

**Comment by johnsolo15** [comment]
This is the error that we get:
```ORA-06550: line 1, column 7:
PLS-00306: wrong number or types of arguments in call to 'ADDORDER'
ORA-06550: line 1, column 7:
PL/SQL: Statement ignored
```
I'm going to work on it today

**Comment by johnsolo15** [comment]
Setting the input for CallableStatement wasn't working correctly using column names. Setting the input with indexes fixed the issue.
