### ISSUE TITLE
Menu Selection Not Accurate

### ISSUE THREAD

**Issue by cbrown405** [johnsolo15/AZ-Penguins#7]
We've noticed menu selection is not 100% accurate and can take you to a completely different menu, this might have to do with the fact that the code is using .nextInt() and such for determining what choice was chosen. We can just skip this with a simple .nextLine() and using .equals() instead. There's also the issue with not selecting a menu item will just exit you out of the application, we should be using the quit options for such.

**Comment by johnsolo15** [comment]
Fixed by adding missing break commands to switch statements.
